### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by masudr4n4** [Bwaim/NewsApp#1]
Hallo sir,I have seen that your app have no logo.I am graphics designer who wants to contribute on  your project by creating a logo for the app.If you have any requirements then let me know.its totally free.

**Comment by Bwaim** [comment]
Hello, if you want to make a logo, no problem.
I don't have any requirement.

**Comment by masudr4n4** [comment]
I made this logo for your apps.
![news app-01](https://user-images.githubusercontent.com/34313493/39883194-e3282782-54a7-11e8-903c-a08e47ba48b2.jpg)

plzz check #2

Thank you.

**Comment by Bwaim** [comment]
@maaudrana the icon you did is for the README.MD file or the app ?

**Comment by masudr4n4** [comment]
yes. if you have any problem add redme.md ?? kindly add app icon in your project.

**Comment by Bwaim** [comment]
Ah because i don't need a logo for the README.MD
